var Canoodle;
(function(e){(function(h){function p(a){a.attr(c.selected,"true");a.parents("menu").attr(c.containsSelected,"true")}function s(){$(a.selected).attr(c.selected,"default");$(a.containsSelected).removeAttr(c.containsSelected)}function t(){$(a.selected).removeAttr(c.selected);$(a.containsSelected).removeAttr(c.containsSelected)}function v(l){function g(){d.removeAttr(c.focused);d.attr(c.selected,"true");d.get().blur()}function w(){var b=$(a.selected);b.is(a.selectable)?b.trigger("click"):b.is(a.scrollable)?
(b.removeAttr(c.selected),b.attr(c.focused,"true")):b.is(a.formfield)?(b.removeAttr(c.selected),b.attr(c.focused,"true"),b.get().focus(),b.one("blur",function(){d.removeAttr(c.focused);d.attr(c.selected,"true")}),l.preventDefault()):console.warn("Unhandled selection event.")}function k(){var b=$(a.selected);if(0==b.length)b=$(a["default"]),0==b.length&&(b=$($(a.target)[0])),p(b);else{var d=b.offset().left+b.offset().width/2,f=b.offset().top+b.offset().height/2,c;switch(l.keyCode){case e.Device.Keys.LEFT:c=
Math.PI;break;case e.Device.Keys.RIGHT:c=0;break;case e.Device.Keys.UP:c=3*Math.PI/2;break;case e.Device.Keys.DOWN:c=1*Math.PI/2}var n=[],g=Infinity;$(a.target).each(function(a){var b=$(this);a=b.offset().left+b.offset().width/2;var l=b.offset().top+b.offset().height/2,b=Math.sqrt(Math.abs(d-a)^2+Math.abs(f-l)^2);0!=b&&(a=Math.atan2(l-f,a-d),0>a&&(a+=2*Math.PI),a-=c,a>Math.PI&&(a-=2*Math.PI),a=Math.abs(a),n.push({target:this,theta:a,delta:b}),a<g&&(g=a))});if(!(g>=Math.PI/2)){var k=Math.PI/2;g<Math.PI/
4&&(k=Math.PI/4);g<Math.PI/16&&(k=Math.PI/16);g<Math.PI/18&&(k=Math.PI/18);n=n.filter(function(a,b,d){return a.theta<k});n.sort(function(a,b){return a.delta-b.delta});t();p($(n[0].target))}}}var d=$(a.focused);switch(l.keyCode){case e.Device.Keys.LEFT:case e.Device.Keys.RIGHT:case e.Device.Keys.UP:case e.Device.Keys.DOWN:if(0<$(a.formfieldFocused).length)break;else if(0<d.length)switch(l.keyCode){case e.Device.Keys.UP:d.get().scrollTop-=50;break;case e.Device.Keys.DOWN:d.get().scrollTop+=50}else u<
(new Date).getTime()&&(k(),q());break;case e.Device.Keys.ESC:0<d.length&&g();break;case e.Device.Keys.ENTER:if(0<d.length){if(d.is("textarea"))break;g()}else w()}}function q(){function c(){var b=$(a.selected).parents(a.carousel.rail).css("transition")?500:0;$(a.selected).parents(a.carousel.rail).css("transition","transform "+b+"ms");$(a.selected).parents(a.carousel.rail).css("-webkit-transition","-webkit-transform "+b+"ms");u=(new Date).getTime()+b}var g=$(a["default"]).offset(),e=$(a.selected).parents(a.carousel.rail).offset(),
k=$(a.selected).parents(a.carousel.mask).offset(),d=0,b=0;$(a.selected).parents(a.carousel.rail).children().each(function(){var a=$(this).offset(),c=a.left-e.left+a.width;c>d&&(d=c);a=a.top-e.top+a.height;a>b&&(b=a)});var m;if(d>k.width){m=g.left-e.left;var f=m/(d-g.width),f=(k.width-g.width)*f;m=-1*Math.round(m-f);c()}else m=k.width/2-d/2;var h;b>k.height?(h=g.top-e.top,f=h/(b-g.height),f*=k.height-g.height,h=-1*Math.round(h-f),c()):h=0;g="translate3d("+m+"px, "+h+"px, 0px)";$(a.selected).parents(a.carousel.rail).css("transform",
g);$(a.selected).parents(a.carousel.rail).css("-webkit-transform",g)}"undefined"==typeof $&&console.warn("The Canoodle Navigation module requires jqMobi (recommended) or jQuery.\njqMobi: http://app-framework-software.intel.com/\njQuery: http://jquery.com/");var c={selected:"data-canoodle-selected",containsSelected:"data-canoodle-contains-selected",focused:"data-canoodle-focused"},a={target:"*[data-canoodle-selectable='default'],*[data-canoodle-selectable='true'],button,input:enabled,textarea,select[multiple],textarea,section[data-canoodle-scroll='auto'],section[data-canoodle-scroll='true']",
selected:"*[data-canoodle-selected='true']","default":"*[data-canoodle-selected='default'],*[data-canoodle-selected='true']",containsSelected:"*[data-canoodle-contains-selected='true']",selectable:"*[data-canoodle-selectable='true'],button,input[type='image']",scrollable:"section[data-canoodle-scroll='auto'],section[data-canoodle-scroll='true']",formfield:"input,textarea,select",focused:"*[data-canoodle-focused='true']",formfieldFocused:"input:focus,textarea:focus,select:focus",carousel:{rail:"*[data-canoodle-container='carousel']",
mask:"*[data-canoodle-container='mask']"}},u=0;h.select=function(c){c=$(c);c.is(a.selectable)?(t(),p(c)):console.warn("Could not select element. The element is not selectable.");q()};h.clearSelected=s;h.getSelected=function(){return $(a.selected).get()};h.update=function(){q()};var r=0;window.addEventListener("keydown",function(a){r=2;v(a)},!1);window.addEventListener("mousemove",function(a){r--;r||s()},!0);(function(a){a.keystroke=function(a,c,e,d,b,h){"undefined"===typeof c&&(c="keydown");"undefined"===
typeof e&&(e=!1);"undefined"===typeof d&&(d=!1);"undefined"===typeof b&&(b=!1);"undefined"===typeof h&&(h=!1);var f=window.document.createEvent("Events");f.initEvent(c,!0,!0);f.ctrlKey=e;f.altKey=d;f.shiftKey=b;f.metaKey=h;f.keyCode=a;f.charCode=0;f.which=f.keyCode;window.dispatchEvent(f)}})(h.Simulate||(h.Simulate={}))})(e.Navigation||(e.Navigation={}))})(Canoodle||(Canoodle={}));
